FROM nginx:alpine

COPY index.html /usr/share/nginx/html/index.html

COPY entrypoint.sh /entrypoint.sh

COPY nginx.conf /etc/nginx/nginx.conf

RUN chmod +x /entrypoint.sh

ENTRYPOINT [ "/entrypoint.sh" ]